// Copyright 2026, The DisplayXR Project and its contributors
// SPDX-License-Identifier: Apache-2.0
/*!
 * @file
 * @brief  Linux Vulkan OpenXR glTF/PBR model viewer (native-Wayland, windowed).
 *
 * WINDOWING (updated): app-owned native Wayland surface via
 * XR_DXR_wayland_surface_binding + XrWaylandSurfaceGeometryDXR (spec-v2, runtime
 * >= v2.18.0). The app creates a wl_surface + xdg-shell toplevel and hands the
 * (wl_display, wl_surface) pair to the runtime, which presents into it — a
 * genuine native-Wayland windowed app (NOT Xwayland). Replaces the prior
 * hosted-NULL path below. DXR_MV_WINDOW="WxH" sets the window size.
 *
 * The Linux arm of displayxr-demo-modelviewer. Renders glTF/STL/OBJ/FBX/USD
 * models on tracked 3D displays via OpenXR + Vulkan, reusing the vendor-neutral
 * model_common/ModelRenderer PBR pipeline shared with the macOS (macos/main.mm)
 * and Windows (windows/main.cpp) entry points.
 *
 * WINDOWING — hosted-NULL (issue #40, M8 Linux epic runtime#699). Unlike the
 * macOS/Windows entries, which own an OS window and pass its handle via
 * XR_DXR_cocoa_window_binding / XR_DXR_win32_window_binding, this entry passes
 * NO window binding: the runtime self-creates a native-resolution window
 * (hosted-NULL). This is the valid interim path per the Linux demo-port
 * playbook (docs/guides/linux-demo-port.md) while the faithful
 * XR_DXR_xlib_window_binding arm is Phase-3b/hardware-gated. It is deliberately
 * headless of any input/HUD/file-dialog stack — this is a BUILD-GREEN target
 * (compiled on CI, not run: CI has no GPU/display). On-screen validation is a
 * separate pass gated on the runtime's Linux present + a GPU + an X server.
 *
 * The frame loop drives ModelRenderer with a fixed framed camera (no live
 * input) so a Linux runtime with a display can present the bundled sample
 * model; it consumes XR_DXR_view_rig render-ready views when the runtime
 * offers them, matching the macOS render path.
 */

#include <vulkan/vulkan.h>

#include <wayland-client.h>              // app-owned native Wayland surface (NOT Xwayland)
#include "xdg-shell-client-protocol.h"  // xdg-shell toplevel (generated by wayland-scanner)
#include "xdg-decoration-unstable-v1-client-protocol.h"  // server-side title bar (generated)
#include <libdecor.h>                    // client-side title bar (GNOME has no SSD)

#define XR_USE_GRAPHICS_API_VULKAN
#include <openxr/openxr.h>
#include <openxr/openxr_platform.h>
#include <openxr/XR_DXR_display_info.h>
#include <openxr/XR_DXR_view_rig.h>
#include <openxr/XR_DXR_wayland_surface_binding.h>

#include <poll.h>                         // non-blocking wl_display fd pump (per frame)

#include <array>
#include <chrono>
#include <cmath>
#include <csignal>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

#include <climits>
#include <libgen.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>

#include "view_params.h"
#include "display3d_view.h"
#include "projection_depth.h"
#include "model_renderer.h"
#include "model_loader.h"
#include "eye_pose_hud.h"

// ============================================================================
// Logging
// ============================================================================

#define LOG_INFO(fmt, ...)  fprintf(stdout, "[INFO]  " fmt "\n", ##__VA_ARGS__)
#define LOG_WARN(fmt, ...)  fprintf(stderr, "[WARN]  " fmt "\n", ##__VA_ARGS__)
#define LOG_ERROR(fmt, ...) fprintf(stderr, "[ERROR] " fmt "\n", ##__VA_ARGS__)

#define XR_CHECK(call) \
    do { \
        XrResult _r = (call); \
        if (XR_FAILED(_r)) { LOG_ERROR("%s failed: %d", #call, (int)_r); return false; } \
    } while (0)

#define VK_CHECK(call) \
    do { \
        VkResult _r = (call); \
        if (_r != VK_SUCCESS) { LOG_ERROR("%s failed: %d", #call, (int)_r); return false; } \
    } while (0)

static volatile bool g_running = true;
static ModelRenderer g_modelRenderer;
static std::string g_loadedFileName;
static uint32_t g_windowW = 1280, g_windowH = 720;

// Camera / fit state (fixed framing — no live input on Linux build-green).
static ViewParams g_viewParams;
static float g_camPos[3] = {0, 0, 0};
static float g_camYaw = 0.0f, g_camPitch = 0.0f;

static constexpr float kDefaultVirtualDisplayHeightM = 1.5f;
static constexpr float kAutoFitVerticalComfort = 1.4f;

// ============================================================================
// Inline math — column-major float[16] (mirrors macos/main.mm)
// ============================================================================

static void mat4_identity(float* m) {
    memset(m, 0, 16 * sizeof(float));
    m[0] = m[5] = m[10] = m[15] = 1.0f;
}
static void mat4_multiply(float* out, const float* a, const float* b) {
    float tmp[16];
    for (int col = 0; col < 4; col++)
        for (int row = 0; row < 4; row++) {
            float sum = 0.0f;
            for (int k = 0; k < 4; k++) sum += a[k * 4 + row] * b[col * 4 + k];
            tmp[col * 4 + row] = sum;
        }
    memcpy(out, tmp, sizeof(tmp));
}
static void mat4_translation(float* m, float tx, float ty, float tz) {
    mat4_identity(m); m[12] = tx; m[13] = ty; m[14] = tz;
}
static void mat4_from_xr_fov(float* m, XrFovf fov, float nearZ, float farZ) {
    float tanL = tanf(fov.angleLeft), tanR = tanf(fov.angleRight);
    float tanU = tanf(fov.angleUp), tanD = tanf(fov.angleDown);
    float w = tanR - tanL, h = tanU - tanD;
    memset(m, 0, 16 * sizeof(float));
    m[0] = 2.0f / w; m[5] = 2.0f / h;
    m[8] = (tanR + tanL) / w; m[9] = (tanU + tanD) / h;
    m[10] = -(farZ + nearZ) / (farZ - nearZ);
    m[11] = -1.0f;
    m[14] = -(2.0f * farZ * nearZ) / (farZ - nearZ);
}
static void mat4_view_from_xr_pose(float* viewMat, XrPosef pose) {
    float qx = pose.orientation.x, qy = pose.orientation.y;
    float qz = pose.orientation.z, qw = pose.orientation.w;
    float rot[16]; mat4_identity(rot);
    rot[0]  = 1 - 2*(qy*qy + qz*qz); rot[1]  = 2*(qx*qy + qz*qw); rot[2]  = 2*(qx*qz - qy*qw);
    rot[4]  = 2*(qx*qy - qz*qw);     rot[5]  = 1 - 2*(qx*qx + qz*qz); rot[6]  = 2*(qy*qz + qx*qw);
    rot[8]  = 2*(qx*qz + qy*qw);     rot[9]  = 2*(qy*qz - qx*qw); rot[10] = 1 - 2*(qx*qx + qy*qy);
    float invRot[16]; mat4_identity(invRot);
    for (int i = 0; i < 3; i++) for (int j = 0; j < 3; j++) invRot[j*4+i] = rot[i*4+j];
    float invTrans[16];
    mat4_translation(invTrans, -pose.position.x, -pose.position.y, -pose.position.z);
    mat4_multiply(viewMat, invRot, invTrans);
}
static void quat_from_yaw_pitch(float yaw, float pitch, XrQuaternionf* out) {
    float cy = cosf(yaw/2), sy = sinf(yaw/2), cp = cosf(pitch/2), sp = sinf(pitch/2);
    out->w = cy*cp; out->x = cy*sp; out->y = sy*cp; out->z = -sy*sp;
}
static void quat_rotate_vec3(XrQuaternionf q, float vx, float vy, float vz,
                             float* ox, float* oy, float* oz) {
    float tx = 2.0f*(q.y*vz - q.z*vy), ty = 2.0f*(q.z*vx - q.x*vz), tz = 2.0f*(q.x*vy - q.y*vx);
    *ox = vx + q.w*tx + (q.y*tz - q.z*ty);
    *oy = vy + q.w*ty + (q.z*tx - q.x*tz);
    *oz = vz + q.w*tz + (q.x*ty - q.y*tx);
}
// Display-local eye Z (matches macos/main.mm RigLocalEyeZ).
static float RigLocalEyeZ(const XrPosef& rig, const XrVector3f& eyeWorld) {
    XrQuaternionf inv = {-rig.orientation.x, -rig.orientation.y, -rig.orientation.z, rig.orientation.w};
    float ox, oy, oz;
    quat_rotate_vec3(inv, eyeWorld.x - rig.position.x, eyeWorld.y - rig.position.y,
                     eyeWorld.z - rig.position.z, &ox, &oy, &oz);
    return oz;
}

// ============================================================================
// App-owned Wayland surface (handle class — XR_DXR_wayland_surface_binding)
// ----------------------------------------------------------------------------
// Native Wayland (NOT Xwayland): connect wl_display, bind wl_compositor +
// xdg_wm_base, create a wl_surface + xdg-shell toplevel, and hand the
// (wl_display*, wl_surface*) pair to the runtime at xrCreateSession. The runtime
// builds its VkSurfaceKHR via VK_KHR_wayland_surface and presents into it. This
// replaces the hosted-NULL path where the runtime self-created the window.
// Windowed interlacing phase comes from the runtime's wl_geom D-Bus consumer
// (window-geometry@displayxr.org GNOME Shell extension) — Wayland never tells a
// client its absolute position, so the app does nothing special for it.
// ============================================================================
static struct wl_display*    g_wlDisplay    = nullptr;
static struct wl_registry*   g_wlRegistry   = nullptr;
static struct wl_compositor* g_wlCompositor = nullptr;
static struct xdg_wm_base*   g_xdgWmBase    = nullptr;
static struct wl_surface*    g_wlSurface    = nullptr;
static struct xdg_surface*   g_xdgSurface   = nullptr;
static struct xdg_toplevel*  g_xdgToplevel  = nullptr;
// xdg-decoration: ask the compositor to draw a server-side title bar. Only used
// on the raw-xdg fallback path; GNOME/Mutter does not advertise this global.
static struct zxdg_decoration_manager_v1*  g_xdgDecorMgr   = nullptr;
static struct zxdg_toplevel_decoration_v1* g_xdgToplevelDecor = nullptr;
// libdecor: client-side title bar (the working path on GNOME, which refuses SSD).
// libdecor internally creates the xdg_surface + xdg_toplevel for our content
// surface and paints the frame on SEPARATE subsurfaces — the content surface the
// runtime weaves stays undecorated. g_useLibdecor selects this path over raw xdg.
static struct libdecor*        g_libdecor      = nullptr;
static struct libdecor_frame*  g_libdecorFrame = nullptr;
static bool                    g_useLibdecor   = false;

static void xdg_wm_base_ping_handler(void*, struct xdg_wm_base* b, uint32_t serial) {
    xdg_wm_base_pong(b, serial);
}
static const struct xdg_wm_base_listener g_xdgWmBaseListener = { xdg_wm_base_ping_handler };

// wl_output tracking: a client can't choose which monitor a WINDOWED toplevel
// opens on (compositor policy), but it CAN fullscreen on a specific wl_output.
// We bind every output at v4 to get its connector name ("DP-1", "eDP-1", ...)
// so DXR_MV_OUTPUT can target the DS1 panel deterministically instead of the
// laptop. See CreateAppWindow.
struct TrackedOutput { struct wl_output* output; char name[64]; int physW; int physH; };
static TrackedOutput g_outputs[8];
static int           g_outputCount = 0;

static void output_geometry(void*, struct wl_output*, int32_t, int32_t, int32_t,
                            int32_t, int32_t, const char*, const char*, int32_t) {}
static void output_mode(void* data, struct wl_output*, uint32_t flags,
                        int32_t width, int32_t height, int32_t) {
    TrackedOutput* to = (TrackedOutput*)data;
    if (to && (flags & WL_OUTPUT_MODE_CURRENT)) { to->physW = width; to->physH = height; }
}
static void output_done(void*, struct wl_output*) {}
static void output_scale(void*, struct wl_output*, int32_t) {}
static void output_name(void* data, struct wl_output*, const char* name) {
    TrackedOutput* to = (TrackedOutput*)data;
    if (to && name) { snprintf(to->name, sizeof(to->name), "%s", name); }
}
static void output_description(void*, struct wl_output*, const char*) {}
static const struct wl_output_listener g_outputListener = {
    output_geometry, output_mode, output_done, output_scale,
    output_name, output_description,
};

static void registry_global(void*, struct wl_registry* reg, uint32_t name,
                            const char* iface, uint32_t version) {
    if (strcmp(iface, wl_compositor_interface.name) == 0) {
        uint32_t v = version < 4 ? version : 4;
        g_wlCompositor = (struct wl_compositor*)wl_registry_bind(reg, name, &wl_compositor_interface, v);
    } else if (strcmp(iface, xdg_wm_base_interface.name) == 0) {
        // Bind xdg_wm_base at v1 (matches the cube): keeps xdg_toplevel from
        // emitting v4+ events we don't handle.
        g_xdgWmBase = (struct xdg_wm_base*)wl_registry_bind(reg, name, &xdg_wm_base_interface, 1);
        xdg_wm_base_add_listener(g_xdgWmBase, &g_xdgWmBaseListener, nullptr);
    } else if (strcmp(iface, zxdg_decoration_manager_v1_interface.name) == 0) {
        g_xdgDecorMgr = (struct zxdg_decoration_manager_v1*)wl_registry_bind(
            reg, name, &zxdg_decoration_manager_v1_interface, 1);
    } else if (strcmp(iface, wl_output_interface.name) == 0 && g_outputCount < 8) {
        uint32_t v = version < 4 ? version : 4;  // v4 gives the `name` event
        TrackedOutput* to = &g_outputs[g_outputCount++];
        to->name[0] = '\0'; to->physW = 0; to->physH = 0;
        to->output = (struct wl_output*)wl_registry_bind(reg, name, &wl_output_interface, v);
        wl_output_add_listener(to->output, &g_outputListener, to);
    }
}
static void registry_global_remove(void*, struct wl_registry*, uint32_t) {}
static const struct wl_registry_listener g_registryListener = { registry_global, registry_global_remove };

static void xdg_surface_configure(void*, struct xdg_surface* s, uint32_t serial) {
    xdg_surface_ack_configure(s, serial);
}
static const struct xdg_surface_listener g_xdgSurfaceListener = { xdg_surface_configure };

static void xdg_toplevel_configure(void*, struct xdg_toplevel*, int32_t w, int32_t h, struct wl_array*) {
    if (w > 0 && h > 0) { g_windowW = (uint32_t)w; g_windowH = (uint32_t)h; }
}
static void xdg_toplevel_close(void*, struct xdg_toplevel*) { g_running = false; }
static void xdg_toplevel_configure_bounds(void*, struct xdg_toplevel*, int32_t, int32_t) {}
static void xdg_toplevel_wm_capabilities(void*, struct xdg_toplevel*, struct wl_array*) {}
static const struct xdg_toplevel_listener g_xdgToplevelListener = {
    xdg_toplevel_configure, xdg_toplevel_close,
    xdg_toplevel_configure_bounds, xdg_toplevel_wm_capabilities,
};

// The compositor acks the decoration mode it actually applied. GNOME/Mutter
// honors SERVER_SIDE and draws its own title bar; if a compositor forces
// CLIENT_SIDE we'd get no bar (and would need to draw one ourselves).
static void xdg_decoration_configure(void*, struct zxdg_toplevel_decoration_v1*,
                                     uint32_t mode) {
    LOG_INFO("xdg-decoration: compositor applied mode=%u (%s)", mode,
             mode == ZXDG_TOPLEVEL_DECORATION_V1_MODE_SERVER_SIDE
                 ? "SERVER_SIDE — title bar drawn by compositor"
                 : "CLIENT_SIDE — no server title bar");
}
static const struct zxdg_toplevel_decoration_v1_listener g_xdgDecorListener = {
    xdg_decoration_configure,
};

// ---- libdecor (client-side decorations) ----
static void libdecor_on_error(struct libdecor*, enum libdecor_error, const char* message) {
    LOG_ERROR("libdecor error: %s", message ? message : "(null)");
}
static struct libdecor_interface g_libdecorIface = {
    libdecor_on_error, {}, {}, {}, {}, {}, {}, {}, {}, {}, {},
};

// A configure arrived: adopt the compositor's content size (or keep ours) and
// commit the decoration state. We do NOT attach a buffer here — the runtime
// presents into the content surface via its swapchain; libdecor only owns the
// frame around it.
static void libdecor_frame_on_configure(struct libdecor_frame* frame,
                                        struct libdecor_configuration* config, void*) {
    int w = 0, h = 0;
    if (!libdecor_configuration_get_content_size(config, frame, &w, &h) || w <= 0 || h <= 0) {
        w = (int)g_windowW; h = (int)g_windowH;   // no size in config → keep current
    }
    g_windowW = (uint32_t)w; g_windowH = (uint32_t)h;
    struct libdecor_state* st = libdecor_state_new(w, h);
    libdecor_frame_commit(frame, st, config);
    libdecor_state_free(st);
}
static void libdecor_frame_on_close(struct libdecor_frame*, void*) { g_running = false; }
static void libdecor_frame_on_commit(struct libdecor_frame*, void*) {
    if (g_wlSurface) wl_surface_commit(g_wlSurface);
}
static void libdecor_frame_on_dismiss_popup(struct libdecor_frame*, const char*, void*) {}
static struct libdecor_frame_interface g_libdecorFrameIface = {
    libdecor_frame_on_configure, libdecor_frame_on_close,
    libdecor_frame_on_commit, libdecor_frame_on_dismiss_popup,
    {}, {}, {}, {}, {}, {}, {}, {}, {}, {},
};

// width/height are the requested toplevel size; the compositor may override via
// configure, tracked in g_windowW/g_windowH. Wayland never lets a client set its
// own absolute position — that is exactly why windowed weaving needs the runtime
// geometry extension.
static bool CreateAppWindow(uint32_t width, uint32_t height) {
    g_wlDisplay = wl_display_connect(nullptr);
    if (!g_wlDisplay) { LOG_ERROR("wl_display_connect failed — is WAYLAND_DISPLAY set?"); return false; }
    g_wlRegistry = wl_display_get_registry(g_wlDisplay);
    wl_registry_add_listener(g_wlRegistry, &g_registryListener, nullptr);
    wl_display_roundtrip(g_wlDisplay);  // fire registry_global for every global
    if (!g_wlCompositor || !g_xdgWmBase) {
        LOG_ERROR("Wayland compositor missing wl_compositor or xdg_wm_base"); return false;
    }
    // Second roundtrip: the wl_output `name` events are delivered after the bind
    // in the first roundtrip. Now g_outputs[].name is populated.
    wl_display_roundtrip(g_wlDisplay);

    // Resolve a target output for fullscreen. DXR_MV_OUTPUT names a connector
    // (e.g. "DP-1" = the DS1 panel). A windowed toplevel can't be placed on a
    // chosen monitor under Wayland, so targeting a specific display REQUIRES
    // fullscreen-on-output. If the named output isn't found we fall back to the
    // first NON-laptop (non-eDP) output so we never open on the laptop.
    const char* outEnv = getenv("DXR_MV_OUTPUT");
    struct wl_output* targetOutput = nullptr;
    const char* targetName = "(compositor-chosen)";
    int targetPhysW = 0, targetPhysH = 0;
    {
        char names[512] = {0};
        for (int i = 0; i < g_outputCount; ++i) {
            char one[96]; snprintf(one, sizeof(one), "%s(%dx%d) ",
                g_outputs[i].name[0] ? g_outputs[i].name : "?", g_outputs[i].physW, g_outputs[i].physH);
            strncat(names, one, sizeof(names) - strlen(names) - 1);
        }
        LOG_INFO("wl_output: %d output(s) available: %s", g_outputCount, names);
        int pick = -1;
        if (outEnv && *outEnv) {
            for (int i = 0; i < g_outputCount; ++i)
                if (strcmp(g_outputs[i].name, outEnv) == 0) { pick = i; break; }
            if (pick < 0) {
                LOG_ERROR("DXR_MV_OUTPUT=%s not found among outputs — using first non-eDP output", outEnv);
                for (int i = 0; i < g_outputCount; ++i)
                    if (strncmp(g_outputs[i].name, "eDP", 3) != 0) { pick = i; break; }
            }
        }
        if (pick >= 0) {
            targetOutput = g_outputs[pick].output; targetName = g_outputs[pick].name;
            targetPhysW = g_outputs[pick].physW;   targetPhysH = g_outputs[pick].physH;
        }
    }

    g_windowW = width; g_windowH = height;
    g_wlSurface = wl_compositor_create_surface(g_wlCompositor);

    // Fullscreen is required to pin the window to a specific monitor; it also
    // gives the crisp full-panel weave. A title bar only applies to a windowed
    // toplevel, so it is mutually exclusive with output targeting / fullscreen.
    const bool wantFullscreen = (getenv("DXR_MV_FULLSCREEN") != nullptr) || (outEnv != nullptr);
    const bool wantTitlebar   = (getenv("DXR_MV_NO_TITLEBAR") == nullptr) && !wantFullscreen;
    static const char* kTitle = "DisplayXR Model Viewer (Wayland)";
    static const char* kAppId = "org.displayxr.model_viewer_handle_vk_wayland";

    // --- Preferred path: libdecor client-side title bar (works on GNOME) ---
    if (wantTitlebar) {
        g_libdecor = libdecor_new(g_wlDisplay, &g_libdecorIface);
        if (g_libdecor) {
            g_libdecorFrame = libdecor_decorate(g_libdecor, g_wlSurface,
                                                &g_libdecorFrameIface, nullptr);
            if (g_libdecorFrame) {
                libdecor_frame_set_title(g_libdecorFrame, kTitle);
                libdecor_frame_set_app_id(g_libdecorFrame, kAppId);
                libdecor_frame_set_capabilities(g_libdecorFrame,
                    (enum libdecor_capabilities)(LIBDECOR_ACTION_MOVE | LIBDECOR_ACTION_RESIZE |
                     LIBDECOR_ACTION_MINIMIZE | LIBDECOR_ACTION_FULLSCREEN | LIBDECOR_ACTION_CLOSE));
                libdecor_frame_map(g_libdecorFrame);
                g_useLibdecor = true;
                // Drive the initial configure/commit handshake so libdecor acks
                // before the runtime attaches its swapchain buffers.
                wl_display_roundtrip(g_wlDisplay);
                libdecor_dispatch(g_libdecor, 0);
                LOG_INFO("libdecor: client-side title bar ENABLED (GTK plugin) — content "
                         "surface %p decorated via subsurfaces", (void*)g_wlSurface);
            } else {
                LOG_ERROR("libdecor_decorate failed — falling back to borderless");
                libdecor_unref(g_libdecor); g_libdecor = nullptr;
            }
        } else {
            LOG_INFO("libdecor_new failed (plugin missing?) — falling back to borderless");
        }
    }

    // --- Fallback path: raw xdg-shell (borderless on GNOME; SSD elsewhere) ---
    if (!g_useLibdecor) {
        g_xdgSurface = xdg_wm_base_get_xdg_surface(g_xdgWmBase, g_wlSurface);
        xdg_surface_add_listener(g_xdgSurface, &g_xdgSurfaceListener, nullptr);
        g_xdgToplevel = xdg_surface_get_toplevel(g_xdgSurface);
        xdg_toplevel_add_listener(g_xdgToplevel, &g_xdgToplevelListener, nullptr);
        xdg_toplevel_set_title(g_xdgToplevel, kTitle);
        xdg_toplevel_set_app_id(g_xdgToplevel, kAppId);
        if (g_xdgDecorMgr && wantTitlebar) {
            g_xdgToplevelDecor = zxdg_decoration_manager_v1_get_toplevel_decoration(
                g_xdgDecorMgr, g_xdgToplevel);
            zxdg_toplevel_decoration_v1_add_listener(g_xdgToplevelDecor, &g_xdgDecorListener, nullptr);
            zxdg_toplevel_decoration_v1_set_mode(
                g_xdgToplevelDecor, ZXDG_TOPLEVEL_DECORATION_V1_MODE_SERVER_SIDE);
            LOG_INFO("xdg-decoration: requested SERVER_SIDE title bar (fallback path)");
        }
        if (wantFullscreen) {
            xdg_toplevel_set_fullscreen(g_xdgToplevel, targetOutput);
            LOG_INFO("fullscreen requested on output %s%s", targetName,
                     targetOutput ? "" : " (compositor picks; set DXR_MV_OUTPUT=DP-1 to force the DS1)");
        }
        // Initial buffer-less commit solicits the first configure; roundtrip so
        // xdg_surface_configure fires + acks before the runtime attaches buffers.
        wl_surface_commit(g_wlSurface);
        wl_display_roundtrip(g_wlDisplay);

        // 1:1 weave fix for fullscreen on a specific panel. The compositor
        // configures the toplevel in LOGICAL px (g_windowW/H, e.g. 1920x1080 on
        // a HiDPI-context surface) but the 3D panel needs a buffer the size of
        // its PHYSICAL pixels (3840x2160). Set buffer_scale = phys/logical and
        // declare the panel's physical size as the surface geometry so the
        // runtime sizes its swapchain to the full panel → buffer == panel == 1:1.
        // Override with DXR_MV_BUFFER_SCALE if the compositor disagrees.
        if (wantFullscreen && targetPhysW > 0 && targetPhysH > 0 && g_windowW > 0) {
            int scale = targetPhysW / (int)g_windowW;
            const char* se = getenv("DXR_MV_BUFFER_SCALE");
            if (se && *se) scale = atoi(se);
            if (scale < 1) scale = 1;
            wl_surface_set_buffer_scale(g_wlSurface, scale);
            g_windowW = (uint32_t)targetPhysW;
            g_windowH = (uint32_t)targetPhysH;
            wl_surface_commit(g_wlSurface);
            wl_display_roundtrip(g_wlDisplay);
            LOG_INFO("fullscreen 1:1 fix: buffer_scale=%d, declared panel geometry %ux%u "
                     "(logical configure was scaled up to physical)", scale, g_windowW, g_windowH);
        }
    }
    LOG_INFO("Created app-owned Wayland surface %p (requested %ux%u; compositor-placed, "
             "position via geometry extension)", (void*)g_wlSurface, g_windowW, g_windowH);
    return true;
}

// Pump the Wayland queue non-blocking, once per frame. The runtime borrows this
// wl_display for its VkSurface but never dispatches it, so the app owns the queue
// (pings, close, configure/size).
static void PumpAppWindowEvents() {
    if (!g_wlDisplay) return;
    if (g_useLibdecor && g_libdecor) {
        // libdecor shares this wl_display; its dispatch pumps both the frame
        // events (drag/close/resize) and the main queue, non-blocking.
        libdecor_dispatch(g_libdecor, 0);
        return;
    }
    while (wl_display_prepare_read(g_wlDisplay) != 0) wl_display_dispatch_pending(g_wlDisplay);
    wl_display_flush(g_wlDisplay);
    struct pollfd pfd = { wl_display_get_fd(g_wlDisplay), POLLIN, 0 };
    if (poll(&pfd, 1, 0) > 0 && (pfd.revents & POLLIN)) wl_display_read_events(g_wlDisplay);
    else wl_display_cancel_read(g_wlDisplay);
    wl_display_dispatch_pending(g_wlDisplay);
}

// Destroy AFTER the session is torn down — the runtime's VkSurface borrows this
// wl_display connection for its lifetime.
static void DestroyAppWindow() {
    // libdecor owns the xdg_surface/toplevel it created; unref it before the
    // content surface + display it borrows.
    if (g_libdecorFrame) { libdecor_frame_unref(g_libdecorFrame); g_libdecorFrame = nullptr; }
    if (g_libdecor)      { libdecor_unref(g_libdecor);            g_libdecor = nullptr; }
    if (g_xdgToplevelDecor) { zxdg_toplevel_decoration_v1_destroy(g_xdgToplevelDecor); g_xdgToplevelDecor = nullptr; }
    if (g_xdgDecorMgr)  { zxdg_decoration_manager_v1_destroy(g_xdgDecorMgr); g_xdgDecorMgr = nullptr; }
    if (g_xdgToplevel)  { xdg_toplevel_destroy(g_xdgToplevel);   g_xdgToplevel = nullptr; }
    if (g_xdgSurface)   { xdg_surface_destroy(g_xdgSurface);     g_xdgSurface = nullptr; }
    if (g_wlSurface)    { wl_surface_destroy(g_wlSurface);       g_wlSurface = nullptr; }
    if (g_xdgWmBase)    { xdg_wm_base_destroy(g_xdgWmBase);      g_xdgWmBase = nullptr; }
    if (g_wlCompositor) { wl_compositor_destroy(g_wlCompositor); g_wlCompositor = nullptr; }
    if (g_wlRegistry)   { wl_registry_destroy(g_wlRegistry);     g_wlRegistry = nullptr; }
    if (g_wlDisplay)    { wl_display_disconnect(g_wlDisplay);    g_wlDisplay = nullptr; }
}

// ============================================================================
// OpenXR session
// ============================================================================

struct AppXrSession {
    XrInstance instance = XR_NULL_HANDLE;
    XrSystemId systemId = XR_NULL_SYSTEM_ID;
    XrSession session = XR_NULL_HANDLE;
    XrSpace localSpace = XR_NULL_HANDLE;
    XrViewConfigurationType viewConfigType = XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO;
    bool sessionRunning = false;
    bool exitRequested = false;
    XrSessionState sessionState = XR_SESSION_STATE_UNKNOWN;
    char systemName[256] = {};

    struct { XrSwapchain swapchain; uint32_t width, height, imageCount; int64_t format; } swapchain = {};

    bool hasDisplayInfoExt = false;
    bool hasViewRigExt = false;
    bool hasWaylandBindingExt = false;
    uint32_t viewWidth = 0, viewHeight = 0;  // runtime-recommended per-eye size (window-based)
    float displayWidthM = 0, displayHeightM = 0;
    float nominalViewerZ = 0.5f;
    uint32_t displayPixelWidth = 0, displayPixelHeight = 0;

    PFN_xrRequestDisplayRenderingModeDXR pfnRequestDisplayRenderingModeEXT = nullptr;
    PFN_xrEnumerateDisplayRenderingModesDXR pfnEnumerateDisplayRenderingModesEXT = nullptr;

    uint32_t renderingModeCount = 0;
    uint32_t renderingModeViewCounts[8] = {};
    float renderingModeScaleX[8] = {};
    float renderingModeScaleY[8] = {};
    bool renderingModeDisplay3D[8] = {};
    uint32_t renderingModeTileColumns[8] = {};
    uint32_t renderingModeTileRows[8] = {};
    uint32_t currentRenderingMode = 1;

    uint32_t maxViewCount = 2;
};

static bool InitializeOpenXR(AppXrSession& xr) {
    uint32_t extCount = 0;
    xrEnumerateInstanceExtensionProperties(nullptr, 0, &extCount, nullptr);
    std::vector<XrExtensionProperties> exts(extCount, {XR_TYPE_EXTENSION_PROPERTIES});
    xrEnumerateInstanceExtensionProperties(nullptr, extCount, &extCount, exts.data());

    bool hasVulkan = false;
    for (const auto& e : exts) {
        if (strcmp(e.extensionName, XR_KHR_VULKAN_ENABLE_EXTENSION_NAME) == 0) hasVulkan = true;
        if (strcmp(e.extensionName, XR_DXR_DISPLAY_INFO_EXTENSION_NAME) == 0) xr.hasDisplayInfoExt = true;
        if (strcmp(e.extensionName, XR_DXR_VIEW_RIG_EXTENSION_NAME) == 0) xr.hasViewRigExt = true;
        if (strcmp(e.extensionName, XR_DXR_WAYLAND_SURFACE_BINDING_EXTENSION_NAME) == 0) xr.hasWaylandBindingExt = true;
    }
    if (!hasVulkan) { LOG_ERROR("XR_KHR_vulkan_enable not available"); return false; }

    std::vector<const char*> enabled;
    enabled.push_back(XR_KHR_VULKAN_ENABLE_EXTENSION_NAME);
    if (xr.hasDisplayInfoExt) enabled.push_back(XR_DXR_DISPLAY_INFO_EXTENSION_NAME);
    if (xr.hasViewRigExt) enabled.push_back(XR_DXR_VIEW_RIG_EXTENSION_NAME);
    LOG_INFO("XR_DXR_view_rig: %s", xr.hasViewRigExt ? "AVAILABLE" : "NOT FOUND");
    // Native-Wayland windowed path: the app owns a wl_surface and hands it to the
    // runtime (XR_DXR_wayland_surface_binding), replacing the old hosted-NULL
    // runtime-self-created window. This is a handle-class app — the binding is
    // mandatory; without it the runtime has no surface to present into.
    LOG_INFO("XR_DXR_wayland_surface_binding: %s", xr.hasWaylandBindingExt ? "AVAILABLE" : "NOT FOUND");
    if (!xr.hasWaylandBindingExt) {
        LOG_ERROR("XR_DXR_wayland_surface_binding not available — needs the DisplayXR "
                  "runtime (v2.18.0+) that supports app-provided Wayland surfaces");
        return false;
    }
    enabled.push_back(XR_DXR_WAYLAND_SURFACE_BINDING_EXTENSION_NAME);

    XrInstanceCreateInfo ci = {XR_TYPE_INSTANCE_CREATE_INFO};
    strncpy(ci.applicationInfo.applicationName, "DisplayXRModelViewerLinux",
            sizeof(ci.applicationInfo.applicationName) - 1);
    ci.applicationInfo.applicationVersion = 1;
    strncpy(ci.applicationInfo.engineName, "None", sizeof(ci.applicationInfo.engineName) - 1);
    ci.applicationInfo.apiVersion = XR_CURRENT_API_VERSION;
    ci.enabledExtensionCount = (uint32_t)enabled.size();
    ci.enabledExtensionNames = enabled.data();
    XR_CHECK(xrCreateInstance(&ci, &xr.instance));

    XrSystemGetInfo si = {XR_TYPE_SYSTEM_GET_INFO};
    si.formFactor = XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY;
    XR_CHECK(xrGetSystem(xr.instance, &si, &xr.systemId));

    { XrSystemProperties sp = {XR_TYPE_SYSTEM_PROPERTIES};
      xrGetSystemProperties(xr.instance, xr.systemId, &sp);
      memcpy(xr.systemName, sp.systemName, sizeof(xr.systemName)); }

    if (xr.hasDisplayInfoExt) {
        XrSystemProperties sp = {XR_TYPE_SYSTEM_PROPERTIES};
        XrDisplayInfoDXR di = {(XrStructureType)XR_TYPE_DISPLAY_INFO_DXR};
        sp.next = &di;
        if (XR_SUCCEEDED(xrGetSystemProperties(xr.instance, xr.systemId, &sp))) {
            xr.displayWidthM = di.displaySizeMeters.width;
            xr.displayHeightM = di.displaySizeMeters.height;
            xr.nominalViewerZ = di.nominalViewerPositionInDisplaySpace.z;
            xr.displayPixelWidth = di.displayPixelWidth;
            xr.displayPixelHeight = di.displayPixelHeight;
        }
        xrGetInstanceProcAddr(xr.instance, "xrRequestDisplayRenderingModeDXR",
                              (PFN_xrVoidFunction*)&xr.pfnRequestDisplayRenderingModeEXT);
        xrGetInstanceProcAddr(xr.instance, "xrEnumerateDisplayRenderingModesDXR",
                              (PFN_xrVoidFunction*)&xr.pfnEnumerateDisplayRenderingModesEXT);
    }
    LOG_INFO("OpenXR initialized: %s", xr.systemName);
    return true;
}

static bool GetVulkanGraphicsRequirements(AppXrSession& xr) {
    PFN_xrGetVulkanGraphicsRequirementsKHR fn = nullptr;
    xrGetInstanceProcAddr(xr.instance, "xrGetVulkanGraphicsRequirementsKHR", (PFN_xrVoidFunction*)&fn);
    if (!fn) return false;
    XrGraphicsRequirementsVulkanKHR req = {XR_TYPE_GRAPHICS_REQUIREMENTS_VULKAN_KHR};
    return XR_SUCCEEDED(fn(xr.instance, xr.systemId, &req));
}

// Parse a space-separated extension list from an xrGetVulkan*ExtensionsKHR call.
static void SplitExtList(const std::string& s, std::vector<std::string>& out) {
    size_t i = 0;
    while (i < s.size()) {
        size_t e = s.find(' ', i); if (e == std::string::npos) e = s.size();
        std::string n = s.substr(i, e - i);
        if (!n.empty() && n[0] != '\0') out.push_back(n);
        i = e + 1;
    }
}

static bool CreateVulkanInstance(AppXrSession& xr, VkInstance& vkInstance) {
    PFN_xrGetVulkanInstanceExtensionsKHR fn = nullptr;
    xrGetInstanceProcAddr(xr.instance, "xrGetVulkanInstanceExtensionsKHR", (PFN_xrVoidFunction*)&fn);
    if (!fn) return false;
    uint32_t bufSize = 0;
    fn(xr.instance, xr.systemId, 0, &bufSize, nullptr);
    std::string extStr(bufSize, '\0');
    fn(xr.instance, xr.systemId, bufSize, &bufSize, extStr.data());
    std::vector<std::string> extNames; SplitExtList(extStr, extNames);
    // Linux: native Vulkan ICD — no MoltenVK portability enumeration (that's a
    // macOS-only requirement; adding it here would fail on a stock Linux loader).
    std::vector<const char*> extPtrs;
    for (auto& n : extNames) extPtrs.push_back(n.c_str());

    VkApplicationInfo ai = {};
    ai.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO;
    ai.pApplicationName = "DisplayXRModelViewerLinux";
    ai.apiVersion = VK_API_VERSION_1_2;
    VkInstanceCreateInfo ci = {};
    ci.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
    ci.pApplicationInfo = &ai;
    ci.enabledExtensionCount = (uint32_t)extPtrs.size();
    ci.ppEnabledExtensionNames = extPtrs.data();
    VK_CHECK(vkCreateInstance(&ci, nullptr, &vkInstance));
    return true;
}

static bool GetVulkanPhysicalDevice(AppXrSession& xr, VkInstance vkInstance, VkPhysicalDevice& pd) {
    PFN_xrGetVulkanGraphicsDeviceKHR fn = nullptr;
    xrGetInstanceProcAddr(xr.instance, "xrGetVulkanGraphicsDeviceKHR", (PFN_xrVoidFunction*)&fn);
    if (!fn) return false;
    XR_CHECK(fn(xr.instance, xr.systemId, vkInstance, &pd));
    VkPhysicalDeviceProperties props; vkGetPhysicalDeviceProperties(pd, &props);
    LOG_INFO("GPU: %s", props.deviceName);
    return true;
}

static bool GetVulkanDeviceExtensions(AppXrSession& xr, std::vector<const char*>& exts,
                                      std::vector<std::string>& storage) {
    PFN_xrGetVulkanDeviceExtensionsKHR fn = nullptr;
    xrGetInstanceProcAddr(xr.instance, "xrGetVulkanDeviceExtensionsKHR", (PFN_xrVoidFunction*)&fn);
    if (!fn) return false;
    uint32_t bufSize = 0;
    fn(xr.instance, xr.systemId, 0, &bufSize, nullptr);
    std::string extStr(bufSize, '\0');
    fn(xr.instance, xr.systemId, bufSize, &bufSize, extStr.data());
    SplitExtList(extStr, storage);
    // No VK_KHR_portability_subset on Linux (MoltenVK-only).
    for (auto& n : storage) exts.push_back(n.c_str());
    return true;
}

static bool FindGraphicsQueueFamily(VkPhysicalDevice pd, uint32_t& idx) {
    uint32_t count = 0; vkGetPhysicalDeviceQueueFamilyProperties(pd, &count, nullptr);
    std::vector<VkQueueFamilyProperties> fams(count);
    vkGetPhysicalDeviceQueueFamilyProperties(pd, &count, fams.data());
    for (uint32_t i = 0; i < count; i++)
        if (fams[i].queueFlags & VK_QUEUE_GRAPHICS_BIT) { idx = i; return true; }
    return false;
}

static bool CreateVulkanDevice(VkPhysicalDevice pd, uint32_t qfi,
                               const std::vector<const char*>& exts, VkDevice& dev, VkQueue& queue) {
    float prio = 1.0f;
    VkDeviceQueueCreateInfo qi = {};
    qi.sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
    qi.queueFamilyIndex = qfi; qi.queueCount = 1; qi.pQueuePriorities = &prio;
    VkPhysicalDeviceFeatures features = {};
    features.shaderInt64 = VK_TRUE;
    features.shaderStorageImageWriteWithoutFormat = VK_TRUE;
    VkDeviceCreateInfo ci = {};
    ci.sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
    ci.queueCreateInfoCount = 1; ci.pQueueCreateInfos = &qi;
    ci.enabledExtensionCount = (uint32_t)exts.size(); ci.ppEnabledExtensionNames = exts.data();
    ci.pEnabledFeatures = &features;
    VK_CHECK(vkCreateDevice(pd, &ci, nullptr, &dev));
    vkGetDeviceQueue(dev, qfi, 0, &queue);
    return true;
}

// Native-Wayland handle class: chain the app-owned Wayland surface (+ its declared
// geometry) onto the Vulkan graphics binding. The runtime builds a VkSurfaceKHR
// from (wl_display, wl_surface) via VK_KHR_wayland_surface and presents into it.
static bool CreateSession(AppXrSession& xr, VkInstance vkInstance, VkPhysicalDevice pd,
                          VkDevice dev, uint32_t qfi) {
    XrGraphicsBindingVulkanKHR vkBinding = {XR_TYPE_GRAPHICS_BINDING_VULKAN_KHR};
    vkBinding.instance = vkInstance;
    vkBinding.physicalDevice = pd;
    vkBinding.device = dev;
    vkBinding.queueFamilyIndex = qfi;
    vkBinding.queueIndex = 0;

    // Hand the app-owned Wayland surface to the runtime. The wl_display connection
    // must outlive the session (the runtime borrows it for the VkSurface lifetime).
    XrWaylandSurfaceBindingCreateInfoDXR wlBinding = {XR_TYPE_WAYLAND_SURFACE_BINDING_CREATE_INFO_DXR};
    wlBinding.next = &vkBinding;
    wlBinding.wlDisplay = g_wlDisplay;
    wlBinding.wlSurface = g_wlSurface;
    wlBinding.transparentBackgroundEnabled = XR_FALSE;

    // XR_DXR_wayland_surface_binding spec-v2 (runtime >= v2.18.0): declare the
    // surface SIZE so the runtime sizes its WSI swapchain + recommended views to
    // our window instead of forcing the whole panel (the pre-v2 fallback, which
    // showed only the top-left quarter at 200%). The v1 header here lacks the
    // struct, so define it inline (ABI: type=1004999251, then w/h/refreshMilliHertz).
#ifndef XR_TYPE_WAYLAND_SURFACE_GEOMETRY_DXR
#define XR_TYPE_WAYLAND_SURFACE_GEOMETRY_DXR ((XrStructureType)1004999251)
    typedef struct XrWaylandSurfaceGeometryDXR {
        XrStructureType          type;
        const void* XR_MAY_ALIAS next;
        uint32_t                 width;
        uint32_t                 height;
        uint32_t                 refreshMilliHertz;
    } XrWaylandSurfaceGeometryDXR;
#endif
    XrWaylandSurfaceGeometryDXR wlGeom = {XR_TYPE_WAYLAND_SURFACE_GEOMETRY_DXR};
    wlGeom.next = &wlBinding;              // chain: session -> wlGeom -> wlBinding -> vkBinding
    wlGeom.width = g_windowW;
    wlGeom.height = g_windowH;
    wlGeom.refreshMilliHertz = 60000;     // 60.000 Hz; 0 keeps the runtime's default

    XrSessionCreateInfo si = {XR_TYPE_SESSION_CREATE_INFO};
    si.next = &wlGeom; si.systemId = xr.systemId;
    XR_CHECK(xrCreateSession(xr.instance, &si, &xr.session));
    LOG_INFO("Session created (Wayland binding: wl_display %p, wl_surface %p; declared geometry %ux%u @60Hz)",
             (void*)g_wlDisplay, (void*)g_wlSurface, g_windowW, g_windowH);

    if (xr.pfnEnumerateDisplayRenderingModesEXT && xr.session != XR_NULL_HANDLE) {
        uint32_t modeCount = 0;
        if (XR_SUCCEEDED(xr.pfnEnumerateDisplayRenderingModesEXT(xr.session, 0, &modeCount, nullptr))
            && modeCount > 0) {
            std::vector<XrDisplayRenderingModeInfoDXR> modes(modeCount);
            for (uint32_t i = 0; i < modeCount; i++) {
                modes[i].type = XR_TYPE_DISPLAY_RENDERING_MODE_INFO_DXR; modes[i].next = nullptr;
            }
            if (XR_SUCCEEDED(xr.pfnEnumerateDisplayRenderingModesEXT(
                    xr.session, modeCount, &modeCount, modes.data()))) {
                xr.renderingModeCount = modeCount > 8 ? 8 : modeCount;
                LOG_INFO("Display rendering modes (%u):", modeCount);
                for (uint32_t i = 0; i < xr.renderingModeCount; i++) {
                    xr.renderingModeViewCounts[i] = modes[i].viewCount;
                    xr.renderingModeScaleX[i] = modes[i].viewScaleX;
                    xr.renderingModeScaleY[i] = modes[i].viewScaleY;
                    xr.renderingModeDisplay3D[i] = (modes[i].hardwareDisplay3D == XR_TRUE);
                    xr.renderingModeTileColumns[i] = modes[i].tileColumns ? modes[i].tileColumns : 1;
                    xr.renderingModeTileRows[i] = modes[i].tileRows ? modes[i].tileRows : 1;
                    LOG_INFO("  [%u] %s (views=%u, scale=%.2fx%.2f, tiles=%ux%u, 3D=%d)",
                             modes[i].modeIndex, modes[i].modeName, modes[i].viewCount,
                             modes[i].viewScaleX, modes[i].viewScaleY,
                             xr.renderingModeTileColumns[i], xr.renderingModeTileRows[i],
                             modes[i].hardwareDisplay3D);
                }
            }
        }
    }
    return true;
}

static bool CreateSpaces(AppXrSession& xr) {
    XrReferenceSpaceCreateInfo ci = {XR_TYPE_REFERENCE_SPACE_CREATE_INFO};
    ci.referenceSpaceType = XR_REFERENCE_SPACE_TYPE_LOCAL;
    ci.poseInReferenceSpace = {{0,0,0,1},{0,0,0}};
    XR_CHECK(xrCreateReferenceSpace(xr.session, &ci, &xr.localSpace));
    return true;
}

static bool CreateSwapchains(AppXrSession& xr) {
    uint32_t viewCount = 0;
    xrEnumerateViewConfigurationViews(xr.instance, xr.systemId, xr.viewConfigType, 0, &viewCount, nullptr);
    std::vector<XrViewConfigurationView> views(viewCount, {XR_TYPE_VIEW_CONFIGURATION_VIEW});
    xrEnumerateViewConfigurationViews(xr.instance, xr.systemId, xr.viewConfigType, viewCount, &viewCount, views.data());
    xr.maxViewCount = viewCount;
    LOG_INFO("View config: %u views reported by runtime", viewCount);

    uint32_t fmtCount = 0;
    xrEnumerateSwapchainFormats(xr.session, 0, &fmtCount, nullptr);
    std::vector<int64_t> fmts(fmtCount);
    xrEnumerateSwapchainFormats(xr.session, fmtCount, &fmtCount, fmts.data());
    int64_t selectedFmt = fmts.empty() ? VK_FORMAT_B8G8R8A8_UNORM : fmts[0];
    for (auto f : fmts) {
        if (f == VK_FORMAT_B8G8R8A8_SRGB || f == VK_FORMAT_R8G8B8A8_SRGB) { selectedFmt = f; break; }
        if (f == VK_FORMAT_B8G8R8A8_UNORM || f == VK_FORMAT_R8G8B8A8_UNORM) selectedFmt = f;
    }

    // Native-Wayland windowed: after we declared XrWaylandSurfaceGeometryDXR, the
    // runtime reports recommendedImageRect sized to our WINDOW and full-height
    // (e.g. 640x720 per eye for a 1280x720 window) — this bakes in scaleX=0.5 but
    // keeps scaleY=1.0, sidestepping the mode-scale view_scale_y=0.5 half-height
    // bug. Size the atlas = recommended per-eye × max tiles across modes, and
    // render each eye at recommended dims (see the main loop). Mirrors the cube.
    xr.viewWidth  = views.empty() ? 640 : views[0].recommendedImageRectWidth;
    xr.viewHeight = views.empty() ? 720 : views[0].recommendedImageRectHeight;
    uint32_t tilesX = 2, tilesY = 1;
    for (uint32_t i = 0; i < xr.renderingModeCount; i++) {
        if (xr.renderingModeTileColumns[i] > tilesX) tilesX = xr.renderingModeTileColumns[i];
        if (xr.renderingModeTileRows[i]    > tilesY) tilesY = xr.renderingModeTileRows[i];
    }
    uint32_t w = xr.viewWidth  * tilesX;
    uint32_t h = xr.viewHeight * tilesY;

    XrSwapchainCreateInfo sci = {XR_TYPE_SWAPCHAIN_CREATE_INFO};
    sci.usageFlags = XR_SWAPCHAIN_USAGE_COLOR_ATTACHMENT_BIT | XR_SWAPCHAIN_USAGE_TRANSFER_DST_BIT;
    sci.format = selectedFmt;
    sci.sampleCount = 1;
    sci.width = w; sci.height = h;
    sci.faceCount = 1; sci.arraySize = 1; sci.mipCount = 1;
    XR_CHECK(xrCreateSwapchain(xr.session, &sci, &xr.swapchain.swapchain));
    xr.swapchain.width = w; xr.swapchain.height = h; xr.swapchain.format = selectedFmt;

    uint32_t imgCount = 0;
    xrEnumerateSwapchainImages(xr.swapchain.swapchain, 0, &imgCount, nullptr);
    xr.swapchain.imageCount = imgCount;
    LOG_INFO("Swapchain: %ux%u, %u images, format=%lld", w, h, imgCount, (long long)selectedFmt);
    return true;
}

static void PollEvents(AppXrSession& xr) {
    XrEventDataBuffer event = {};
    event.type = XR_TYPE_EVENT_DATA_BUFFER;
    while (xrPollEvent(xr.instance, &event) == XR_SUCCESS) {
        if (event.type == XR_TYPE_EVENT_DATA_SESSION_STATE_CHANGED) {
            auto* ssc = (XrEventDataSessionStateChanged*)&event;
            xr.sessionState = ssc->state;
            if (ssc->state == XR_SESSION_STATE_READY) {
                XrSessionBeginInfo bi = {XR_TYPE_SESSION_BEGIN_INFO};
                bi.primaryViewConfigurationType = xr.viewConfigType;
                xrBeginSession(xr.session, &bi);
                xr.sessionRunning = true;
            } else if (ssc->state == XR_SESSION_STATE_STOPPING) {
                xrEndSession(xr.session);
                xr.sessionRunning = false;
            } else if (ssc->state == XR_SESSION_STATE_EXITING) {
                xr.exitRequested = true;
            }
        }
        event.type = XR_TYPE_EVENT_DATA_BUFFER;
    }
}

static bool BeginFrame(AppXrSession& xr, XrFrameState& fs) {
    fs = {XR_TYPE_FRAME_STATE};
    if (XR_FAILED(xrWaitFrame(xr.session, nullptr, &fs))) return false;
    return XR_SUCCEEDED(xrBeginFrame(xr.session, nullptr));
}
static bool AcquireSwapchainImage(AppXrSession& xr, uint32_t& imageIndex) {
    XrSwapchainImageAcquireInfo ai = {XR_TYPE_SWAPCHAIN_IMAGE_ACQUIRE_INFO};
    if (XR_FAILED(xrAcquireSwapchainImage(xr.swapchain.swapchain, &ai, &imageIndex))) return false;
    XrSwapchainImageWaitInfo wi = {XR_TYPE_SWAPCHAIN_IMAGE_WAIT_INFO};
    wi.timeout = 1000000000;
    return XR_SUCCEEDED(xrWaitSwapchainImage(xr.swapchain.swapchain, &wi));
}
static void ReleaseSwapchainImage(AppXrSession& xr) {
    XrSwapchainImageReleaseInfo ri = {XR_TYPE_SWAPCHAIN_IMAGE_RELEASE_INFO};
    xrReleaseSwapchainImage(xr.swapchain.swapchain, &ri);
}
static void EndFrame(AppXrSession& xr, XrTime displayTime,
                     XrCompositionLayerProjectionView* projViews, uint32_t viewCount) {
    XrCompositionLayerProjection layer = {XR_TYPE_COMPOSITION_LAYER_PROJECTION};
    layer.space = xr.localSpace;
    layer.viewCount = viewCount;
    layer.views = projViews;
    const XrCompositionLayerBaseHeader* layers[] = {(const XrCompositionLayerBaseHeader*)&layer};
    XrFrameEndInfo ei = {XR_TYPE_FRAME_END_INFO};
    ei.displayTime = displayTime;
    ei.environmentBlendMode = XR_ENVIRONMENT_BLEND_MODE_OPAQUE;
    ei.layerCount = 1; ei.layers = layers;
    xrEndFrame(xr.session, &ei);
}
static void CleanupOpenXR(AppXrSession& xr) {
    if (xr.swapchain.swapchain) xrDestroySwapchain(xr.swapchain.swapchain);
    if (xr.localSpace) xrDestroySpace(xr.localSpace);
    if (xr.session) xrDestroySession(xr.session);
    if (xr.instance) xrDestroyInstance(xr.instance);
}

// ============================================================================
// Bundled-scene auto-load
// ============================================================================

static std::string ExeDir() {
    char buf[PATH_MAX];
    ssize_t n = readlink("/proc/self/exe", buf, sizeof(buf) - 1);
    if (n <= 0) return "";
    buf[n] = '\0';
    return std::string(dirname(buf));
}
static bool FileExists(const std::string& p) {
    struct stat st; return stat(p.c_str(), &st) == 0 && S_ISREG(st.st_mode);
}

static void ApplyAutoFitForLoadedScene() {
    float center[3], extent[3];
    if (g_modelRenderer.getRobustSceneBounds(0.05f, 0.95f, center, extent)) {
        g_camPos[0] = center[0]; g_camPos[1] = center[1]; g_camPos[2] = center[2];
        float vh = extent[1] * kAutoFitVerticalComfort;
        if (!(vh > 1e-3f)) vh = kDefaultVirtualDisplayHeightM;
        g_viewParams.virtualDisplayHeight = vh;
        LOG_INFO("Auto-fit: center=(%.3f,%.3f,%.3f) vHeight=%.3f", center[0], center[1], center[2], vh);
    } else {
        g_viewParams.virtualDisplayHeight = kDefaultVirtualDisplayHeightM;
    }
    g_camYaw = 0.0f; g_camPitch = 0.0f;
    g_viewParams.scaleFactor = 1.0f;
}

static void TryAutoLoadBundledScene() {
    std::string dir = ExeDir();
    if (dir.empty()) return;
    std::string path = dir + "/sample.glb";
    if (!FileExists(path)) { LOG_INFO("No bundled model at %s (skipping)", path.c_str()); return; }
    if (!model_validate_file(path)) return;
    LOG_INFO("Auto-loading bundled model: %s", path.c_str());
    if (g_modelRenderer.loadModel(path.c_str())) {
        g_loadedFileName = model_basename(path);
        LOG_INFO("Loaded %s (%s)", g_loadedFileName.c_str(), model_filesize_str(path).c_str());
        ApplyAutoFitForLoadedScene();
    } else {
        LOG_WARN("Auto-load failed for %s", path.c_str());
    }
}

static void SignalHandler(int) { g_running = false; }

// ============================================================================
// main
// ============================================================================

int main() {
    setvbuf(stdout, NULL, _IONBF, 0);
    setvbuf(stderr, NULL, _IONBF, 0);
    signal(SIGINT, SignalHandler);
    signal(SIGTERM, SignalHandler);

    LOG_INFO("=== DisplayXR 3D Model Viewer (Vulkan, Linux / native Wayland) ===");

    // Requested window size (logical px). Wayland can't self-position, so any
    // +X+Y offset is N/A; DXR_MV_WINDOW="WxH" overrides the default 1280x720.
    g_windowW = 1280; g_windowH = 720;
    if (const char* wenv = getenv("DXR_MV_WINDOW")) {
        unsigned ww = 0, hh = 0;
        if (sscanf(wenv, "%ux%u", &ww, &hh) == 2 && ww && hh) { g_windowW = ww; g_windowH = hh; }
    }

    AppXrSession xr = {};
    if (!InitializeOpenXR(xr)) { LOG_ERROR("OpenXR init failed"); return 1; }
    // Create the app-owned Wayland surface BEFORE the session — xrCreateSession
    // borrows (wl_display, wl_surface) via the binding chain.
    if (!CreateAppWindow(g_windowW, g_windowH)) {
        LOG_ERROR("Wayland window create failed"); CleanupOpenXR(xr); return 1;
    }
    if (!GetVulkanGraphicsRequirements(xr)) { CleanupOpenXR(xr); return 1; }

    VkInstance vkInstance = VK_NULL_HANDLE;
    if (!CreateVulkanInstance(xr, vkInstance)) { CleanupOpenXR(xr); return 1; }
    VkPhysicalDevice physDevice = VK_NULL_HANDLE;
    if (!GetVulkanPhysicalDevice(xr, vkInstance, physDevice)) {
        vkDestroyInstance(vkInstance, nullptr); CleanupOpenXR(xr); return 1; }
    std::vector<const char*> devExts; std::vector<std::string> extStorage;
    if (!GetVulkanDeviceExtensions(xr, devExts, extStorage)) {
        vkDestroyInstance(vkInstance, nullptr); CleanupOpenXR(xr); return 1; }
    uint32_t queueFamilyIndex = 0;
    if (!FindGraphicsQueueFamily(physDevice, queueFamilyIndex)) {
        vkDestroyInstance(vkInstance, nullptr); CleanupOpenXR(xr); return 1; }
    VkDevice vkDevice = VK_NULL_HANDLE; VkQueue graphicsQueue = VK_NULL_HANDLE;
    if (!CreateVulkanDevice(physDevice, queueFamilyIndex, devExts, vkDevice, graphicsQueue)) {
        vkDestroyInstance(vkInstance, nullptr); CleanupOpenXR(xr); return 1; }
    if (!CreateSession(xr, vkInstance, physDevice, vkDevice, queueFamilyIndex)) {
        vkDestroyDevice(vkDevice, nullptr); vkDestroyInstance(vkInstance, nullptr);
        CleanupOpenXR(xr); return 1; }
    if (!CreateSpaces(xr) || !CreateSwapchains(xr)) {
        CleanupOpenXR(xr); vkDestroyDevice(vkDevice, nullptr);
        vkDestroyInstance(vkInstance, nullptr); return 1; }

    std::vector<XrSwapchainImageVulkanKHR> swapchainImages(
        xr.swapchain.imageCount, {XR_TYPE_SWAPCHAIN_IMAGE_VULKAN_KHR});
    { uint32_t count = xr.swapchain.imageCount;
      xrEnumerateSwapchainImages(xr.swapchain.swapchain, count, &count,
          (XrSwapchainImageBaseHeader*)swapchainImages.data()); }

    if (!g_modelRenderer.init(vkInstance, physDevice, vkDevice, graphicsQueue,
                              queueFamilyIndex, xr.swapchain.width, xr.swapchain.height))
        LOG_WARN("model renderer init failed");

    // Debug eye-pose overlay (#778): on-panel readout of the located per-eye pose.
    EyePoseHud g_hud;
    bool hudOn = (getenv("MV_NO_EYEPOSE_HUD") == nullptr);
    if (hudOn && !g_hud.init(physDevice, vkDevice, graphicsQueue, queueFamilyIndex)) {
        LOG_WARN("eye-pose HUD init failed (continuing without it)");
        hudOn = false;
    }

    // NOTE: do NOT override g_windowW/H with displayPixel* here — that was the
    // hosted-NULL full-panel behavior. We keep the app-owned window size so the
    // render tiles match the window-based atlas (CreateSwapchains / render loop).
    xr.currentRenderingMode = xr.renderingModeCount > 1 ? 1 : 0;

    TryAutoLoadBundledScene();

    LOG_INFO("=== Entering main loop (headless build-green; fixed framing) ===");
    auto lastTime = std::chrono::high_resolution_clock::now();

    while (g_running && !xr.exitRequested) {
        auto now = std::chrono::high_resolution_clock::now();
        float dt = std::chrono::duration<float>(now - lastTime).count();
        lastTime = now;

        // Assert the app's default 3D rendering mode once the session is running.
        if (xr.sessionRunning && xr.pfnRequestDisplayRenderingModeEXT && xr.session != XR_NULL_HANDLE)
            xr.pfnRequestDisplayRenderingModeEXT(xr.session, xr.currentRenderingMode);

        g_modelRenderer.updateAnimation(dt);
        PumpAppWindowEvents();   // wayland: pings, close, configure/size
        PollEvents(xr);

        if (!xr.sessionRunning) { struct timespec ts{0, 50 * 1000 * 1000}; nanosleep(&ts, nullptr); continue; }

        XrFrameState frameState;
        if (!BeginFrame(xr, frameState)) continue;

        std::vector<XrCompositionLayerProjectionView> projectionViews;
        bool rendered = false;
        std::vector<std::string> g_hudLines;   // #778 eye-pose readout for this frame

        if (frameState.shouldRender) {
            XrViewLocateInfo locateInfo = {XR_TYPE_VIEW_LOCATE_INFO};
            locateInfo.viewConfigurationType = xr.viewConfigType;
            locateInfo.displayTime = frameState.predictedDisplayTime;
            locateInfo.space = xr.localSpace;

            XrPosef cameraPose;
            quat_from_yaw_pitch(g_camYaw, g_camPitch, &cameraPose.orientation);
            cameraPose.position = {g_camPos[0], g_camPos[1], g_camPos[2]};
            const float rigVH = g_viewParams.virtualDisplayHeight / g_viewParams.scaleFactor;

            const bool useRig = xr.hasViewRigExt && xr.displayWidthM > 0 && xr.displayHeightM > 0;
            XrDisplayRigDXR displayRig = {XR_TYPE_DISPLAY_RIG_DXR};
            if (useRig) {
                displayRig.pose = cameraPose;
                displayRig.virtualDisplayHeight = rigVH;
                displayRig.ipdFactor = g_viewParams.ipdFactor;
                displayRig.parallaxFactor = g_viewParams.parallaxFactor;
                displayRig.perspectiveFactor = g_viewParams.perspectiveFactor;
                locateInfo.next = &displayRig;
            }

            uint32_t runtimeViewCount = xr.maxViewCount > 0 ? xr.maxViewCount : 2;
            if (runtimeViewCount > 8) runtimeViewCount = 8;
            XrView views[8] = {};
            for (uint32_t v = 0; v < runtimeViewCount; v++) views[v].type = XR_TYPE_VIEW;
            XrViewState viewState = {XR_TYPE_VIEW_STATE};
            // #778 eye-pose HUD: ask the runtime for the RAW predicted eye
            // positions it feeds the rig — the same eye_pos the 3D-GATE log prints
            // (David's "pinned at (0,0.1,0.6)" value). Chained on viewState; the
            // runtime fills it in xrLocateViews (OXR_GET_OUTPUT_FROM_CHAIN).
            XrViewDisplayRawDXR viewRaw = {XR_TYPE_VIEW_DISPLAY_RAW_DXR};
            if (hudOn) viewState.next = &viewRaw;

            XrResult lr = xrLocateViews(xr.session, &locateInfo, &viewState,
                                        runtimeViewCount, &runtimeViewCount, views);
            if (XR_SUCCEEDED(lr) &&
                (viewState.viewStateFlags & XR_VIEW_STATE_POSITION_VALID_BIT) &&
                (viewState.viewStateFlags & XR_VIEW_STATE_ORIENTATION_VALID_BIT)) {

                // #778 eye-pose HUD: capture the RAW located per-eye pose here,
                // before the rig path below rewrites views[].pose. This is exactly
                // what the runtime returns from xrLocateViews — the value David
                // says "is not changing" on head-move.
                if (hudOn) {
                    const XrVector3f zero{0, 0, 0};
                    const XrVector3f& L = viewRaw.eyeCountOutput > 0 ? viewRaw.rawEyes[0] : zero;
                    const XrVector3f& R = viewRaw.eyeCountOutput > 1 ? viewRaw.rawEyes[1]
                                        : (viewRaw.eyeCountOutput > 0 ? viewRaw.rawEyes[0] : zero);
                    static bool havePrev = false;
                    static XrVector3f prevL{0, 0, 0};
                    float dx = L.x - prevL.x, dy = L.y - prevL.y, dz = L.z - prevL.z;
                    float delta = havePrev ? std::sqrt(dx * dx + dy * dy + dz * dz) : 0.0f;
                    prevL = L; havePrev = true;
                    char b[96];
                    g_hudLines.clear();
                    g_hudLines.emplace_back("EYE POSE RAW DXR");
                    std::snprintf(b, sizeof b, "L X:%+.3f Y:%+.3f Z:%+.3f", L.x, L.y, L.z); g_hudLines.emplace_back(b);
                    std::snprintf(b, sizeof b, "R X:%+.3f Y:%+.3f Z:%+.3f", R.x, R.y, R.z); g_hudLines.emplace_back(b);
                    std::snprintf(b, sizeof b, "TRACKING:%d EYES:%d", (int)viewRaw.isTracking, (int)viewRaw.eyeCountOutput); g_hudLines.emplace_back(b);
                    std::snprintf(b, sizeof b, "DELTA:%.4f %s", delta, delta > 1e-4f ? "MOVING" : "STATIC"); g_hudLines.emplace_back(b);
                }

                uint32_t m = xr.currentRenderingMode;
                uint32_t modeViewCount = (xr.renderingModeCount > 0 && m < xr.renderingModeCount)
                    ? xr.renderingModeViewCounts[m] : 2u;
                if (modeViewCount < 1) modeViewCount = 1;
                if (modeViewCount > runtimeViewCount) modeViewCount = runtimeViewCount;
                bool display3D = (xr.renderingModeCount > 0) ? xr.renderingModeDisplay3D[m] : true;
                bool monoMode = !display3D;
                uint32_t tileColumns = (xr.renderingModeCount > 0 && xr.renderingModeTileColumns[m] > 0)
                    ? xr.renderingModeTileColumns[m] : (monoMode ? 1u : 2u);
                int eyeCount = monoMode ? 1 : (int)modeViewCount;

                // Render each eye at the runtime's recommended (window-based,
                // full-height) view size — matches the atlas from CreateSwapchains
                // and the cube's proven native-Wayland path (sidesteps the
                // mode-scale view_scale_y=0.5 half-height bug).
                uint32_t renderW = xr.viewWidth  ? xr.viewWidth  : 640;
                uint32_t renderH = xr.viewHeight ? xr.viewHeight : 720;

                // Consume the runtime's render-ready rig views (XR_DXR_view_rig).
                std::vector<Display3DView> eyeViews((size_t)eyeCount);
                bool hasKooima = useRig;
                if (useRig) {
                    std::vector<XrView> srcViews;
                    if (monoMode && modeViewCount >= 1) {
                        XrView cv = views[0];
                        XrVector3f c = {0,0,0}; XrFovf f = {0,0,0,0};
                        for (uint32_t v = 0; v < modeViewCount; v++) {
                            c.x += views[v].pose.position.x; c.y += views[v].pose.position.y; c.z += views[v].pose.position.z;
                            f.angleLeft += views[v].fov.angleLeft; f.angleRight += views[v].fov.angleRight;
                            f.angleUp += views[v].fov.angleUp; f.angleDown += views[v].fov.angleDown;
                        }
                        float inv = 1.0f / (float)modeViewCount;
                        cv.pose.position = {c.x*inv, c.y*inv, c.z*inv};
                        cv.fov = {f.angleLeft*inv, f.angleRight*inv, f.angleUp*inv, f.angleDown*inv};
                        srcViews.assign(1, cv);
                    } else {
                        for (int e = 0; e < eyeCount; e++)
                            srcViews.push_back(views[e < (int)runtimeViewCount ? e : 0]);
                    }
                    for (int eye = 0; eye < eyeCount; eye++) {
                        const XrView& sv = srcViews[eye];
                        float ez = RigLocalEyeZ(cameraPose, sv.pose.position);
                        float near_z = (ez - rigVH > 1e-4f) ? (ez - rigVH) : 1e-4f;
                        float far_z  = ez + 1000.0f * rigVH;
                        mat4_view_from_xr_pose(eyeViews[eye].view_matrix, sv.pose);
                        mat4_from_xr_fov(eyeViews[eye].projection_matrix, sv.fov, near_z, far_z);
                        convert_projection_gl_to_zero_to_one(eyeViews[eye].projection_matrix);
                        eyeViews[eye].fov = sv.fov;
                        eyeViews[eye].eye_world = sv.pose.position;
                        eyeViews[eye].orientation = sv.pose.orientation;
                        eyeViews[eye].near_z = near_z; eyeViews[eye].far_z = far_z;
                    }
                }

                uint32_t imageIndex;
                if (AcquireSwapchainImage(xr, imageIndex)) {
                    rendered = true;
                    projectionViews.assign((size_t)eyeCount, {XR_TYPE_COMPOSITION_LAYER_PROJECTION_VIEW});
                    std::vector<std::array<float,16>> viewMat((size_t)eyeCount), projMat((size_t)eyeCount);
                    std::vector<std::pair<uint32_t,uint32_t>> tileOffsets((size_t)eyeCount);
                    for (int eye = 0; eye < eyeCount; eye++) {
                        int srcView = eye < (int)runtimeViewCount ? eye : 0;
                        if (hasKooima) {
                            memcpy(viewMat[eye].data(), eyeViews[eye].view_matrix, sizeof(float)*16);
                            memcpy(projMat[eye].data(), eyeViews[eye].projection_matrix, sizeof(float)*16);
                            views[srcView].pose.position = eyeViews[eye].eye_world;
                            views[srcView].pose.orientation = cameraPose.orientation;
                        } else {
                            mat4_view_from_xr_pose(viewMat[eye].data(), views[srcView].pose);
                            mat4_from_xr_fov(projMat[eye].data(), views[srcView].fov, 0.01f, 100.0f);
                        }
                        uint32_t tileX = (uint32_t)(eye % (int)tileColumns);
                        uint32_t tileY = (uint32_t)(eye / (int)tileColumns);
                        uint32_t vpX = tileX * renderW, vpY = tileY * renderH;
                        tileOffsets[eye] = {vpX, vpY};
                        auto& pv = projectionViews[eye];
                        pv.type = XR_TYPE_COMPOSITION_LAYER_PROJECTION_VIEW;
                        pv.subImage.swapchain = xr.swapchain.swapchain;
                        pv.subImage.imageRect.offset = {(int32_t)vpX, (int32_t)vpY};
                        pv.subImage.imageRect.extent = {(int32_t)renderW, (int32_t)renderH};
                        pv.subImage.imageArrayIndex = 0;
                        pv.pose = views[srcView].pose;
                        pv.fov = hasKooima ? eyeViews[eye].fov : views[srcView].fov;
                    }

                    if (g_modelRenderer.hasModel()) {
                        VkImage targetImage = swapchainImages[imageIndex].image;
                        VkFormat swapFormat = (VkFormat)xr.swapchain.format;
                        for (int eye = 0; eye < eyeCount; eye++)
                            g_modelRenderer.renderEye(targetImage, swapFormat,
                                xr.swapchain.width, xr.swapchain.height,
                                tileOffsets[eye].first, tileOffsets[eye].second,
                                renderW, renderH, viewMat[eye].data(), projMat[eye].data());
                        // #778: overlay the eye-pose readout into each eye tile
                        // (after the model, before release — image is COLOR_ATTACHMENT).
                        if (hudOn && !g_hudLines.empty())
                            g_hud.render(targetImage, tileOffsets, g_hudLines);
                    }
                    ReleaseSwapchainImage(xr);
                }
            }
        }

        if (rendered) {
            EndFrame(xr, frameState.predictedDisplayTime,
                     projectionViews.data(), (uint32_t)projectionViews.size());
        } else {
            XrFrameEndInfo ei = {XR_TYPE_FRAME_END_INFO};
            ei.displayTime = frameState.predictedDisplayTime;
            ei.environmentBlendMode = XR_ENVIRONMENT_BLEND_MODE_OPAQUE;
            ei.layerCount = 0; ei.layers = nullptr;
            xrEndFrame(xr.session, &ei);
        }
    }

    if (hudOn) g_hud.destroy();
    g_modelRenderer.cleanup();
    if (vkDevice) vkDeviceWaitIdle(vkDevice);
    CleanupOpenXR(xr);
    // Destroy the Wayland surface AFTER the session — the runtime's VkSurface
    // borrowed this wl_display for the session lifetime.
    DestroyAppWindow();
    if (vkDevice) vkDestroyDevice(vkDevice, nullptr);
    if (vkInstance) vkDestroyInstance(vkInstance, nullptr);
    LOG_INFO("Clean exit");
    return 0;
}
